# Generated by Django 5.1.2 on 2024-10-18 00:47

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swim_drill',
            name='drillname',
            field=banjo.models.StringField(default=''),
        ),
    ]
