# Generated by Django 5.1.2 on 2024-10-24 04:17

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_swim_drill_drillname'),
    ]

    operations = [
        migrations.AddField(
            model_name='swim_drill',
            name='likes',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
